### ISSUE TITLE
Certain special characters yield malformed output

### ISSUE THREAD

**Issue by pteridin** [pteridin/flexlsx#2]
Just saw that gtsummary output with "less than x" content will get malformed to e.g.:

```
<r><rPr/><t>8 (<0.1%)</t></r>
```

- Need to escape those characters

**Comment by JanMarvin** [comment]
This should be escaped in openxlsx2. We simply never came across this. `fmt_txt()` should call `escape_xml()`

**Comment by pteridin** [comment]
Thank you @JanMarvin!

Weaved in a workaround for older openxlsx2 versions <= 0.8.0.9000 that is more or less your implementation of escaping the non-illegal, though troublesome, characters.
