### ISSUE TITLE
Implement better output checking

### ISSUE THREAD

**Issue by pteridin** [pteridin/flexlsx#20]
Versions of flexslx before 0.1.4 relied upon checking the output with a hash function on the XLSX output, which cumbersome in many regards. 0.1.4 will include checking the output differently by comparing the output with the tools that openxlsx2 provides us. This should hopefully improve the checks that we are making, but the checks themselves need to be more handcrafted.

We need:
- [x] Checks for the content
- [ ] Checks for the cell styling
- [ ] Checks for the content styling
- [ ] ...?

**Comment by JanMarvin** [comment]
Hi @pteridin ,

maybe something like this:

```R
library(flexlsx)

ft <- flextable::as_flextable(table(mtcars[,1:2]))
wb <- openxlsx2::wb_workbook()$add_worksheet("mtcars")
wb <- wb_add_flextable(wb, "mtcars", ft, dims = "C2")

cell_styles <- wb$get_cell_style(dims = "C2:H55")
# a tool to check the dimensions from the flextable might be good
# addition in future releases.
# I'm still planning to add a strict check in openxlsx2, if x fits into
# dims. Someday soon™ we might throw a warning if a size
# mismatch is detected.
```

and compare it with this one in the test? I don't know how extensively you want to test. I'd probably just add certain `known` difficult constellations that you expect to potentially break when making changes in `flexlsx` or `openxlsx2`.

In addition to `wb_get_cell_style()`, you could also take a look at `wb$worksheets[[1]]$sheet_data$cc`. This is where all the worksheet information ends up, or you can examine the `wb$styles_mgr$styles` to check the styles created by `openxlsx2`.

**Comment by pteridin** [comment]
Hi @JanMarvin,

Yes, I already thought about using  `get_cell_style` - the function that currently checks the content already retrieves the dimensions of the table. 

I'm also thinking about how intensive I want to make the test. It's worth considering just going for the difficult cases, because otherwise I'm afraid the tests will be bigger than the actual package behind them.

**Comment by pteridin** [comment]
Currently not at capacity to implement further checks. Will implement further checks if any new issues occur.
