### ISSUE TITLE
issue with numbers stored as text output excel file

### ISSUE THREAD

**Issue by quarkoniumm** [pteridin/flexlsx#25]
Although they are defined as numeric values ​​in the original flextable object, after exporting to workbook using wb_add_flextable
and saving to excel file, the numbers are exported as text values.

Only after copying and pasting, I get the option to convert it to numbers.

**Comment by pteridin** [comment]
Thank you @quarkoniumm for pointing that out. I already thought about implementing the option to convert to numerics in the output as well, but I like it as the default behavior to not convert numerics unless specified by the user explicitly. @JanMarvin already provided a quick workaround for the problem, but the final solution might look a little different.

**Comment by pteridin** [comment]
@JanMarvin provided a way of converting the character numbers to text using 

```r
options("openxlsx2.string_nums" = TRUE)
``` 

This fix can already be found in the branch [str_to_num](https://github.com/pteridin/flexlsx/tree/str_to_num) and will be included in the main branch and later versions of flexlsx after I have added a description of this option. A release of these changes on CRAN is not planned yet, unless you really need it @quarkoniumm.

**Comment by quarkoniumm** [comment]
Thank you for fast solution. As far as I'm concerned, it can wait for next release with other planned changes.
