### ISSUE TITLE
Can't export flextable with no header

### ISSUE THREAD

**Issue by jolahy** [pteridin/flexlsx#28]
Hi,
When I delete the flextable's header, I'm unable to export the table. Could you help fix this issue?
Thank you.

**Comment by pteridin** [comment]
Could you provide a short example?

jolahy ***@***.***> schrieb am Mo., 9. Sept. 2024, 06:14:

**Comment by pteridin** [comment]
Thank you. Just a small fix was needed to deal with this little bugger. You need a CRAN release right or does an install of the main git branch suffice for you?

**Comment by jolahy** [comment]
The main git branch install suffices for now. 
Thanks
