### ISSUE TITLE
Some merged cells have no borders

### ISSUE THREAD

**Issue by JanMarvin** [pteridin/flexlsx#3]
I had a look at `flexlsx`. Please feel free to close any issue you don't want to work on.

In the example are actually three or four issues in this one example

* The caption is a cell longer than the table
* In the caption `<br>` should be replaced by `\n` and the cell be wrapped?
* The merged cells in rows 4, 9, 13 and 18 should provide a long border on top
* The column size should be relative to the column name. This one is a bit tricky: `openxlsx2` provides an auto column width option, though that might not be the most reliable. See bottom of the page for a discussion why.

The examples are from the flextable galery: https://www.ardata.fr/en/flextable-gallery/

```R
library(flextable)
library(flexlsx)
library(openxlsx2)

library(officer)
library(dplyr)
library(safetyData)

use_df_printer()

set_flextable_defaults(
  border.color = "#AAAAAA", font.family = "Arial",
  font.size = 10, padding = 2, line_spacing = 1.5
)
adsl <- select(adam_adsl, AGE, SEX, BMIBLGR1, DURDIS, ARM)
# adsl


dat <- summarizor(adsl, by = "ARM")
# dat

ft <- as_flextable(dat, spread_first_col = TRUE, separate_with = "variable") %>%
  bold(i = ~ !is.na(variable), j = 1, bold = TRUE) %>%
  set_caption(
    autonum = officer::run_autonum(seq_id = "tab", bkm = "demo_tab", bkm_all = FALSE),
    fp_p = officer::fp_par(text.align = "left", padding = 5),
    align_with_table = FALSE,
    caption = as_paragraph(
      "Demographic Characteristics",
      "\nx.x: Study Subject Data"
    )
  ) %>%
  add_footer_lines("Source: ADaM adsl data frame from r package 'safetyData'") %>%
  fix_border_issues() %>%
  autofit()

ft

wb <- openxlsx2::wb_workbook()$add_worksheet("mtcars", grid_lines = FALSE)

# add the flextable ft to the workbook, sheet "mtcars"
# offset the table to cell 'C2'
wb <- wb_add_flextable(wb, "mtcars", ft, dims = "C2")

wb$open()
```

## why is `openxlsx2` auto width not the most reliable?

It's because various parameters have to be checked to get the actual width correctly. Let's begin with characters. There are e.g. tabs `nchar("a\tb")` and utf8 characters `nchar("&amp;")` that `nchar` is not getting correct. Similar linebreaks `nchar("a\nb")` this should be the maximum size of each line. But _only_ if `wrap_text` is set. Else it is the full line. Oh and with shared strings the actual cell contains only a zero based index to the shared string table. 
And then there are (unevaluated) formulas and stuff gets nasty very quick `"Total:" & SUM("A1:A10")` (this size most likely is zero all the time). 
Oh and there are numbers with number formats and you have to construct the number format correctly to get the right size.
Did I mention that the width calculation is some dark magic based on the actual font size values?
With sort cells you have additional buttons that have to be added to the width!

Long story short, it is a mammoth of a a task to really fix auto size calculation and it's unlikely to get tackled in `openxlsx2`. Maybe we add some changes here and there, but capturing every possible change is not on my TODO-List.

But with `flexlsx` a few things could be handled  that are `flextable` related. E.g. set wrap_text where required. Get the maximum width based on either the column name or the column width, maybe there even is some hardcoded width value that can be used?

Finally an example to visualize the naugthty `wb_col_widths(width = "auto")`:

``` r
library(openxlsx2)
  
df <- data.frame(
  placebo = "20000000",
  `very_long_drug_name\nsecond_row` = "2000000",
  check.names = FALSE
)

wb <- wb_workbook()$
  add_worksheet()$add_data(x = df)$
  set_col_widths(cols = "A:B", widths = "auto")$
  add_cell_style(dims = "A1:B2", wrap_text = TRUE)

df <- wb_to_df(wb, col_names = FALSE)
apply(df, 2, nchar)
#>   A  B
#> 1 7 30
#> 2 8  7

wb$worksheets[[1]]$cols_attr
#> [1] "<col min=\"1\" max=\"1\" bestFit=\"1\" customWidth=\"1\" hidden=\"false\" width=\"8.711\"/>" 
#> [2] "<col min=\"2\" max=\"2\" bestFit=\"1\" customWidth=\"1\" hidden=\"false\" width=\"31.711\"/>"

if (interactive()) wb$open()
```

**Comment by pteridin** [comment]
Thank you!

1) The caption is a cell longer than the table

Obviously, needs a fix.

2) In the caption <br> should be replaced by \n and the cell be wrapped?

I guess this would make sense.

3) The merged cells in rows 4, 9, 13 and 18 should provide a long border on top

This one is interesting and I will dive deeper into this topic. Currently I don't even understand why flextable draws a border there. But this is only a quick analysis on my end:

```r
df_styles |> 
   select(row_id, col_id, border.width.bottom, border.color.bottom, border.style.bottom) |> 
   unnest_legacy() |> 
   filter(row_id == 7) |> 
   knitr::kable()
```

| row_id| col_id| border.width.bottom|border.color.bottom |border.style.bottom |
|------:|------:|-------------------:|:-------------------|:-------------------|
|      7|      1|                0.75|#AAAAAA             |solid               |
|      7|      2|                **0.00**|#AAAAAA             |solid               |
|      7|      3|                0.75|#AAAAAA             |solid               |
|      7|      4|                **0.00**|#AAAAAA             |solid               |
|      7|      5|                0.75|#AAAAAA             |solid               |
|      7|      6|                **0.00**|#AAAAAA             |solid               |
|      7|      7|                0.75|#AAAAAA             |solid               |

Zero-Borders is no borders from my point of view. Is there another source for border-widths in flextable?

4) The column size should be relative to the column name. This one is a bit tricky: openxlsx2 provides an auto column width option, though that might not be the most reliable. See bottom of the page for a discussion why.

Oh god.

**Comment by JanMarvin** [comment]
My smartphone battery is a bit low, but quick answers for 3 and 4.

3. I didn't check this in flextable, I simply compared the visual output against the Excel file. Might be something internal, after all there's no guarantee that flextable does not fill cells in between. Maybe 0.75 is an indicator to fill empty cells in between.

4. haha, well I was just giving a somewhat detailed explanation. Simply passing some value might be enough. If you care at all ;)

**Comment by JanMarvin** [comment]
There appears to be a column width. From my initial draft:
```R
# some column width
  colwidth <- round(ft$header$colwidths * 9.14400, 0)
  wb$set_col_widths(cols = seq_len(ft_width), widths = colwidth)
```

**Comment by pteridin** [comment]
Okay, got it. 

I need to look into row 8 not 7. This row has an alternating border-top of .75 and 0 that gets merged into one row spanning the entire table. It should be possible to set styles according to the top-left most corner of a merge, then applying styles again. Though, the output still looks a little fishy in this example due to the fact that there is a complete border-top on the cells below cells that have alternating border-bottoms. This just looks ugly. 

Still need to work on this one, but then I can probably present a solution for 1-4, including column-width hell that seems to be solved by flextable.

**Comment by pteridin** [comment]
Fixed most of the issues. Will open another one for the row-heights
