### ISSUE TITLE
images are not handled

### ISSUE THREAD

**Issue by JanMarvin** [pteridin/flexlsx#6]
Not sure how important this is, but currently images are not handled (the table will not be written at all). The path to the image is in `img_data` and could be added per cell via `wb_add_image()`(if someone really wants this), but currently this happens:

```R
> wb <- wb_add_flextable(wb, "mtcars", ft, dims = "C2")
Error in `map()`:
ℹ In index: 1.
ℹ With name: content.
Caused by error in `dplyr::bind_rows()`:
! Can't combine `..1$img_data` <list> and `..6$img_data` <character>.
```

There are other cases that are not possible with Excel like cells that coalesce text and images (in the flextable gallery: the Mario Cart example or the Tennis Players). In Excel the image is not part of the cell, but some overlay that is placed onto the worksheet canvas and can be positioned relative to a cell. So it would be possible to leave some whitespace and position an image exactly where it is supposed to be, but nah ... nobody wants to go down that rabbit hole.

```R
library(flextable)
library(flexlsx)
library(data.table)

z <- as.data.table(ggplot2::diamonds)
z <- z[, list(
  price = mean(price, na.rm = TRUE),
  list_col = list(.SD$x)
), by = "cut"]
z

ft <- flextable(data = z) |>
  compose(j = "list_col", value = as_paragraph(
    plot_chunk(value = list_col, type = "dens", col = "pink",
               width = 1.5, height = .4, free_scale = TRUE)
  )) |>
  colformat_double(big.mark = " ", suffix = " $") |>
  set_header_labels(list_col = "density") |>
  autofit()
ft

ft$body$content$content$data[1, 1]
ft$body$content$content$data[1, 3]

wb <- openxlsx2::wb_workbook()$add_worksheet("mtcars")

# add the flextable ft to the workbook, sheet "mtcars"
# offset the table to cell 'C2'
wb <- wb_add_flextable(wb, "mtcars", ft, dims = "C2")

wb$open()
```

**Comment by pteridin** [comment]
I see you were quite busy testing my package. Thank you! :)

> nobody wants to go down that rabbit hole

That was my take on this matter right from the start. Won't fix unless there is someone with an urgent need for this function and someone that would like to implement that (probably not me?!). Totally out of scope right now, but if the matter arises again, sure. Maybe. In the long run.

**Comment by JanMarvin** [comment]
> I see you were quite busy testing my package. Thank you! :)

I had a moment and was interested to see what works and if there are things `openxlsx2` related that need my attention. I even had a look at the code, but all this piping stuff is like another foreign language in R. These issues were not pressing at all, it's just that I was sure people will stumble over some of these sooner or later :)
